name = "site"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-12-13"

[build]
command = "npm run build"

[site]
bucket = "dist" # directory with your static assets
entry-point = "server" # JS folder serving your assets
