[package]
authors = ["Manu <manu@builder.io>"]
name = "qwik-core"
version = "0.2.0"
edition = "2021"
repository = "https://github.com/BuilderIO/qwik"
license = "MIT"
description = "Qwik optimizer compiler"
keywords = ["qwik", "swc", "javascript", "optimizer", "compiler"]
categories = ["development-tools", "development-tools::cargo-plugins"]

[lib]
crate-type = ["rlib"]

[dependencies]
swc_ecmascript = { version = "0.205.61", features = ["codegen", "utils", "visit", "parser", "transforms", "typescript", "react", "optimization"] }
swc_common = { version = "0.29.13", features = ["sourcemap"] }
swc_atoms = "0.4.24"
serde = "1.0.147"
serde_bytes = "0.11.7"
serde_json = "1.0.87"
simple-error = "0.2.3"
base64 = "0.13.1"
pathdiff = "0.2.1"
relative-path = "1.7.2"
lazy_static = "1.4.0"
anyhow = "1.0.66"
derivative = "2.2.0"
rayon = "1.5.3"
path-slash="0.2.1"

[dev-dependencies]
insta = "1.21.0"

[features]
fs=[]
parallel=[]
