name: Qwik CI

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    name: 'Release'
    description: 'Publish to NPM, and create a Github release.'
    inputs:
      disttag:
        description: 'Workflow will publish to NPM, push the git tag and create a Github release. Enter the NPM Dist Tag to use, such as: latest, next, dev.'
        required: true
        default: 'latest'

env:
  # Disable incremental build, speeds up CI
  CARGO_INCREMENTAL: 0

jobs:
  changes:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      fullbuild: ${{ steps.filter.outputs.fullbuild == 'true' || github.event.inputs.disttag != '' }}

    steps:
      - name: Branch
        run: echo ${{ github.head_ref }}
      - name: NPM Dist Tag
        run: echo "${{ github.event.inputs.disttag }}"
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            fullbuild:
              - 'src/**/*.ts'
              - 'src/**/*.tsx'
              - 'src/**/*.js'
              - 'src/**/*.mjs'
              - 'src/**/*.cjs'
              - 'src/**/*.jsx'
              - 'src/**/*.toml'
              - 'src/**/*.rs'
              - 'src/**/*.lock'
              - 'yarn.lock'
              - 'tsconfig.json'
      - name: Print fullbuild output
        run: echo ${{ steps.filter.outputs.fullbuild == 'true' || github.event.inputs.disttag != '' }}

  ############ BUILD PACKAGE ############
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Build Package
        run: node scripts --tsc --build --api --set-dist-tag="${{ github.event.inputs.disttag }}"

      - name: Print Package Dist Build
        run: tree dist-dev/@builder.io-qwik/

      - name: Upload Package Build Artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist-dev-builder-io-qwik
          path: dist-dev/@builder.io-qwik/
          if-no-files-found: error

      - name: Build Create Qwik CLI
        run: node scripts --cli

      - name: Print Create Qwik CLI Dist Build
        run: tree dist-dev/create-qwik/

      - name: Upload Create Qwik CLI Build Artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist-dev-create-qwik
          path: dist-dev/create-qwik/
          if-no-files-found: error

  ############ BUILD WASM ############
  build-wasm:
    name: Build WASM
    runs-on: ubuntu-latest

    needs: changes

    steps:
      - name: Print fullbuild output
        run: echo ${{ needs.changes.outputs.fullbuild }}

      - name: Setup Node
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install Rust toolchain
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: 1.59.0
          target: wasm32-unknown-unknown

      - name: Checkout
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/checkout@v2

      - name: Cache NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Cache cargo dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: cargo-deps-wasm-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Cache cargo build
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: src/wasm/target
          key: cargo-build-wasm-${{ runner.os }}-${{ hashFiles('./src/wasm/Cargo.lock') }}

      - name: Install NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Build WASM
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: node scripts --wasm --set-dist-tag="${{ github.event.inputs.disttag }}"

      - name: Print WASM Dist Build
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: tree dist-dev/@builder.io-qwik/bindings/

      - name: Upload WASM Build Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: dist-bindings-wasm
          path: dist-dev/@builder.io-qwik/bindings/*
          if-no-files-found: error

  ############ BUILD PLATFORM BINDINGS ############
  build-bindings:
    strategy:
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: yarn build.platform

          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              export SDKROOT=$(xcrun -sdk macosx11.1 --show-sdk-path)
              export MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.1 --show-sdk-platform-version)
              yarn build.platform --platform-target=aarch64-apple-darwin

          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: yarn build.platform

    name: Build ${{ matrix.settings.target }}
    runs-on: ${{ matrix.settings.host }}

    needs: changes

    defaults:
      run:
        working-directory: ./src/napi/

    steps:
      - name: Checkout
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/checkout@v2

      - name: Setup Node
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install Rust toolchain
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          override: true
          toolchain: 1.59.0
          target: ${{ matrix.settings.target }}

      - name: Cache NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ matrix.settings.target }}-${{ hashFiles('yarn.lock') }}

      - name: Pull Latest Image
        if: ${{ needs.changes.outputs.fullbuild == 'true' && matrix.settings.docker }}
        run: ${{ matrix.settings.docker }}
        env:
          DOCKER_REGISTRY_URL: ghcr.io
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache cargo dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: cargo-deps-${{ matrix.settings.target }}-${{ hashFiles('Cargo.lock') }}

      - name: Cache cargo build
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: target
          key: cargo-build-${{ matrix.settings.target }}-${{ hashFiles('Cargo.lock') }}

      - name: Setup Toolchain
        if: ${{ needs.changes.outputs.fullbuild == 'true' && matrix.settings.setup }}
        run: ${{ matrix.settings.setup }}
        shell: bash

      - name: Install NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Build Platform Binding
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: ${{ matrix.settings.build }}
        shell: bash

      - name: Upload Platform Binding Artifact
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: dist-bindings-${{ matrix.settings.target }}
          path: dist-dev/@builder.io-qwik/bindings/*.node
          if-no-files-found: error

  ############ BUILD DISTRIBUTION ############
  build-distribution:
    name: Build Distribution
    runs-on: ubuntu-latest

    needs:
      - build-package
      - build-wasm
      - build-bindings
      - test-unit
      - validate-rust
      - changes

    steps:
      - name: Setup Node
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Create dist-dev/@builder.io-qwik directory
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: |
          mkdir dist-dev/
          mkdir dist-dev/@builder.io-qwik/
          mkdir dist-dev/@builder.io-qwik/bindings/

      - name: Download Build Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/download-artifact@v2

      - name: Print Distribution Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: tree dist-dev-builder-io-qwik/

      - name: Move Distribution Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: mv dist-dev-builder-io-qwik/* dist-dev/@builder.io-qwik/

      - name: Print Bindings Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: tree dist-bindings-*/

      - name: Move Binding Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: mv dist-bindings-*/* dist-dev/@builder.io-qwik/bindings/

      - name: Print dist-dev
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: tree dist-dev/

      - name: Upload Qwik Distribution Artifact
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/upload-artifact@master
        with:
          name: builderio-qwik-distribution
          path: dist-dev/@builder.io-qwik/*
          if-no-files-found: error

  ############ RELEASE ############
  release:
    name: Release
    runs-on: ubuntu-latest

    needs:
      - build-distribution
      - test-e2e
      - changes
    if: ${{ needs.changes.outputs.fullbuild == 'true' }}

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2

      - name: Print Distribution Artifacts
        run: tree builderio-qwik-distribution/

      - name: Print Create Qwik CLI Artifacts
        run: tree dist-dev-create-qwik/

      - name: Move Distribution Artifacts
        run: |
          mkdir dist-dev/
          mkdir dist-dev/@builder.io-qwik/
          mv builderio-qwik-distribution/* dist-dev/@builder.io-qwik/
          mkdir dist-dev/create-qwik/
          mv dist-dev-create-qwik/* dist-dev/create-qwik/

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Dry-Run Publish @builder.io/qwik
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: node scripts --set-dist-tag="${{ github.event.inputs.disttag }}" --release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @builder.io/qwik
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: node scripts --set-dist-tag="${{ github.event.inputs.disttag }}" --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' && github.event_name == 'push' }}
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: yarn qwik-save-artifacts

  ############ E2E TEST ############
  test-e2e:
    name: E2E Tests
    needs:
      - build-distribution
      - changes

    strategy:
      matrix:
        settings:
          - host: ubuntu-latest
            browser: chromium
            node: 16.x
          - host: macos-latest
            browser: webkit
            node: 14.x
          - host: windows-latest
            browser: firefox
            node: 12.x

    runs-on: ${{ matrix.settings.host }}

    steps:
      - name: Setup Node ${{ matrix.settings.node }}
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.settings.node }}
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/download-artifact@v2

      - name: Move Distribution Artifacts
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: |
          mkdir dist-dev/
          mkdir dist-dev/@builder.io-qwik/
          mv builderio-qwik-distribution/* dist-dev/@builder.io-qwik/
          mkdir dist-dev/create-qwik/
          mv dist-dev-create-qwik/* dist-dev/create-qwik/

      - name: Cache NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-node${{ matrix.settings.node }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Install Playwright
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: npx playwright install ${{ matrix.settings.browser }} && npx playwright install-deps ${{ matrix.settings.browser }}

      - name: Playwright E2E Tests
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: yarn test.e2e.${{ matrix.settings.browser }}

      - name: Validate Create Qwik Cli
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: node scripts/validate-cli.cjs

  ############ UNIT TEST ############
  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs:
      - changes

    steps:
      - name: Setup Node
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Checkout
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/checkout@v2

      - name: Cache NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM Dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Jest Unit Tests
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        run: yarn test.unit

  ########### VALIDATE RUST ############
  validate-rust:
    name: Validate Rust
    runs-on: ubuntu-latest

    needs: changes

    steps:
      - name: Checkout repository
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59.0
          profile: default
          override: true

      - name: Cache cargo dependencies
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: cargo-deps-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Cache cargo build
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions/cache@v2
        with:
          path: target
          key: cargo-build-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Format check
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Build check
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

      - name: Clippy check
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features

      - name: Unit tests
        if: ${{ needs.changes.outputs.fullbuild == 'true' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

  ########### LINT PACKAGE ############
  lint-package:
    name: Lint Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: Prettier Check
        if: ${{ always() }}
        run: yarn lint.prettier

      - name: ESLint Check
        if: ${{ always() }}
        run: yarn lint.eslint
